// Certificate PDF generation service (Block 7)
// Uses pdf-lib to create an A4 PDF with certificate data, QR code, and signature.
// Strictly typed, no `any`, UTF‑8 output via Node APIs only.

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import QRCode from 'qrcode';
import { db } from '../db/index.js';

/**
 * Creates a PDF for a certificate identified by its publicId.
 * Returns a Uint8Array containing the PDF bytes.
 */
export async function createPdf(publicId: string): Promise<Uint8Array> {
  // Fetch certificate record – must include public_record JSON.
  const cert = db
    .prepare('SELECT public_record FROM certificates WHERE public_id = ?')
    .get(publicId) as { public_record: string } | undefined;

  if (!cert) {
    throw new Error('Certificate not found');
  }

  const record = JSON.parse(cert.public_record);

  // Basic fields expected (see PLAN.md):
  const { instrument_id, business_name, valid_from, valid_to, hash, signature, keyId } = record;

  // Create a new PDF document.
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4 size in points.

  // Load a standard font.
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontSize = 12;
  const lineHeight = 16;
  let y = page.getHeight() - 72; // top margin.

  const drawLabel = (label: string, value: string) => {
    page.drawText(`${label}: ${value}`, {
      x: 72,
      y,
      size: fontSize,
      font,
      color: rgb(0, 0, 0),
    });
    y -= lineHeight;
  };

  drawLabel('Public ID', publicId);
  drawLabel('Instrument ID', String(instrument_id ?? ''));
  drawLabel('Business', String(business_name ?? ''));
  drawLabel('Valid From', String(valid_from ?? ''));
  drawLabel('Valid To', String(valid_to ?? ''));
  drawLabel('Hash', String(hash ?? ''));
  drawLabel('Signature', String(signature ?? ''));
  drawLabel('Key ID', String(keyId ?? ''));

  // Generate QR code linking to the public verification page.
  const publicBase = process.env.PUBLIC_BASE_URL || 'https://example.com';
  const qrData = `${publicBase}/v/${publicId}`;
  const qrPng = await QRCode.toDataURL(qrData, { margin: 1, width: 150 });
  const qrImageBytes = Buffer.from(qrPng.split(',')[1], 'base64');
  const qrImage = await pdfDoc.embedPng(qrImageBytes);
  const qrDims = qrImage.scale(1);
  page.drawImage(qrImage, {
    x: page.getWidth() - qrDims.width - 72,
    y: page.getHeight() - qrDims.height - 72,
    width: qrDims.width,
    height: qrDims.height,
  });

  // Footer note.
  page.drawText('Generated by NISHCHAY prototype', {
    x: 72,
    y: 36,
    size: 10,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}

/**
 * Exported service object to match import style used elsewhere.
 */
export const certificatePdfService = { createPdf };
